name: 提交插件
description: 申请上架插件市场
title: "[插件申请] "
labels: ["plugin-submit"]
body:
  - type: input
    id: name
    attributes:
      label: "插件昵称"
      placeholder: "例：消息转发插件"
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: "作者"
      placeholder: "GitHub 用户名或昵称"
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: "描述"
      placeholder: "50字以内"
    validations:
      required: true
  - type: input
    id: repo
    attributes:
      label: "仓库地址"
      placeholder: "https://github.com/user/repo"
    validations:
      required: true
  - type: dropdown
    id: tag
    attributes:
      label: "标签"
      options:
        - OneBot
        - QQ
    validations:
      required: true
  - type: checkboxes
    id: check
    attributes:
      label: 确认
      options:
        - label: 仓库公开可访问
          required: true
        - label: 不含恶意代码
          required: true